<?php

use Training\TodoList\Block\Frontend\TodoListBlock;

/**
 * @var TodoListBlock $todoList
 */
$todoList = $block->getTodoList();

?>

<div data-bind="scope: 'todo'">
    <label for="POST-name">Текст:</label>
    <input id="new_task" type="text" name="text" data-bind="value: task" />
    <input type="button" value="Добавить" data-bind="click: create" />

    <ul data-bind="foreach: tasks">

    </ul>

    <!-- <ul id="todo_list">
        <?php if (count($todoList) > 0): ?>
            <?php foreach ($todoList as $item): ?>
                <li>
                    <span>
                        <?= $item->getText(); ?>
                    </span>
                    <?php if ($item->getIsComplete()): ?>
                        <span style="color: green;">(Completed)</span>
                    <?php else: ?>
                        <span style="color: red;">(Pending)</span>
                    <?php endif; ?>
                    <form action="/todo/todo/update" method="post">
                        <input type="hidden" name="id" value="<?= $item->getId() ?>">
                        <input type="hidden" name="is_complete" value="<?= !$item->getIsComplete() ?>">
                        <input type="submit" value="<?= !$item->getIsComplete() ? 'Выполнено' : "Не выполнено" ?>" />
                    </form>
                    <form action="/todo/todo/delete" method="post">
                        <input type="hidden" name="id" value="<?= $item->getId() ?>">
                        <input type="submit" value="Удалить" />
                    </form>
                </li>
            <?php endforeach; ?>
        <?php else: ?>
            <li>No items found.</li>
        <?php endif; ?>
    </ul> -->
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "todo": {
                        "component": "Training_TodoList/js/todo",
                        "createUrl": "/todo/todo/create",
                        "getUrl": "/todo/todo/todo",
                        "updateUrl": "/todo/todo/update",
                        "deleteUrl": "/todo/todo/delete"
                    }
                }
            }
        }
    }
</script>